{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5aed8938-598d-4c1f-98e9-ebe42ae13f9c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ResponseId</th>\n",
       "      <th>MainBranch</th>\n",
       "      <th>Age</th>\n",
       "      <th>EdLevel</th>\n",
       "      <th>Employment</th>\n",
       "      <th>EmploymentAddl</th>\n",
       "      <th>WorkExp</th>\n",
       "      <th>LearnCodeChoose</th>\n",
       "      <th>LearnCode</th>\n",
       "      <th>LearnCodeAI</th>\n",
       "      <th>...</th>\n",
       "      <th>AIAgentOrchestration</th>\n",
       "      <th>AIAgentOrchWrite</th>\n",
       "      <th>AIAgentObserveSecure</th>\n",
       "      <th>AIAgentObsWrite</th>\n",
       "      <th>AIAgentExternal</th>\n",
       "      <th>AIAgentExtWrite</th>\n",
       "      <th>AIHuman</th>\n",
       "      <th>AIOpen</th>\n",
       "      <th>ConvertedCompYearly</th>\n",
       "      <th>JobSat</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>Caring for dependents (children, elderly, etc.)</td>\n",
       "      <td>8.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>Vertex AI</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChatGPT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers</td>\n",
       "      <td>Troubleshooting, profiling, debugging</td>\n",
       "      <td>61256.0</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Associate degree (A.A., A.S., etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I want to...</td>\n",
       "      <td>All skills. AI is a flop.</td>\n",
       "      <td>104413.0</td>\n",
       "      <td>9.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Independent contractor, freelancer, or self-em...</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>10.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChatGPT;Claude Code;GitHub Copilot;Google Gemini</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I want to...</td>\n",
       "      <td>Understand how things actually work, problem s...</td>\n",
       "      <td>53061.0</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>4.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Other online resources (e.g. standard search, ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChatGPT;Claude Code</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I want to...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>36197.0</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "      <td>Independent contractor, freelancer, or self-em...</td>\n",
       "      <td>Caring for dependents (children, elderly, etc.)</td>\n",
       "      <td>21.0</td>\n",
       "      <td>No, I am not new to coding and did not learn n...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers</td>\n",
       "      <td>critical thinking, the skill to define the tas...</td>\n",
       "      <td>60000.0</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>45-54 years old</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "      <td>Independent contractor, freelancer, or self-em...</td>\n",
       "      <td>Caring for dependents (children, elderly, etc....</td>\n",
       "      <td>15.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools req...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>GitHub Copilot</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I have ethical or security concerns about...</td>\n",
       "      <td>designing the architecture in the new domain</td>\n",
       "      <td>120000.0</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>7</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Some college/university study without earning ...</td>\n",
       "      <td>Independent contractor, freelancer, or self-em...</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>9.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Videos (not associated with specific online co...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Sentry</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChatGPT;Claude Code;Google Gemini</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I need he...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>6240.0</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Professional degree (JD, MD, Ph.D, Ed.D, etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>Engaged in paid work (20-29 hours per week);Tr...</td>\n",
       "      <td>22.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Books / Physical media;Technical documentation...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I want to learn best practices;When I wan...</td>\n",
       "      <td>Innovation, system design</td>\n",
       "      <td>72000.0</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>9</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>Caring for dependents (children, elderly, etc....</td>\n",
       "      <td>9.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>70000.0</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>7.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Other online resources (e.g. standard search, ...</td>\n",
       "      <td>No, I learned something that was not related t...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I’m stuck and can’t explain the problem;W...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>5400.0</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>11</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>7.0</td>\n",
       "      <td>No, I am not new to coding and did not learn n...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Spring AI</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChatGPT;Claude Code;GitHub Copilot;Microsoft C...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I have et...</td>\n",
       "      <td>Code writing. I know this sounds weird but you...</td>\n",
       "      <td>65691.0</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>12</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>18-24 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>None of the above</td>\n",
       "      <td>3.0</td>\n",
       "      <td>No, I am not new to coding and did not learn n...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools for...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I don’t trust AI’s answers;When I need qu...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>14400.0</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>13</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Independent contractor, freelancer, or self-em...</td>\n",
       "      <td>Caring for dependents (children, elderly, etc.)</td>\n",
       "      <td>10.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Videos (not associated with specific online co...</td>\n",
       "      <td>No, I learned something that was not related t...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>When I want to fully understand something;When...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1099.0</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>14</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>Caring for dependents (children, elderly, etc.)</td>\n",
       "      <td>6.0</td>\n",
       "      <td>Yes, I am not new to coding but am learning ne...</td>\n",
       "      <td>Online Courses or Certification (includes all ...</td>\n",
       "      <td>Yes, I learned how to use AI-enabled tools req...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>15</td>\n",
       "      <td>I am a developer by profession</td>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>Professional degree (JD, MD, Ph.D, Ed.D, etc.)</td>\n",
       "      <td>Employed</td>\n",
       "      <td>Attending school (full-time);Attending school ...</td>\n",
       "      <td>15.0</td>\n",
       "      <td>No, I am not new to coding and did not learn n...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>No, I learned something that was not related t...</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>I don’t think I’ll need help from people anymore</td>\n",
       "      <td>senior development</td>\n",
       "      <td>NaN</td>\n",
       "      <td>9.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>15 rows × 172 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "    ResponseId                      MainBranch              Age  \\\n",
       "0            1  I am a developer by profession  25-34 years old   \n",
       "1            2  I am a developer by profession  25-34 years old   \n",
       "2            3  I am a developer by profession  35-44 years old   \n",
       "3            4  I am a developer by profession  35-44 years old   \n",
       "4            5  I am a developer by profession  35-44 years old   \n",
       "5            6  I am a developer by profession  45-54 years old   \n",
       "6            7  I am a developer by profession  25-34 years old   \n",
       "7            8  I am a developer by profession  35-44 years old   \n",
       "8            9  I am a developer by profession  25-34 years old   \n",
       "9           10  I am a developer by profession  25-34 years old   \n",
       "10          11  I am a developer by profession  25-34 years old   \n",
       "11          12  I am a developer by profession  18-24 years old   \n",
       "12          13  I am a developer by profession  35-44 years old   \n",
       "13          14  I am a developer by profession  25-34 years old   \n",
       "14          15  I am a developer by profession  35-44 years old   \n",
       "\n",
       "                                              EdLevel  \\\n",
       "0     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   \n",
       "1                 Associate degree (A.A., A.S., etc.)   \n",
       "2        Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "3        Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "4     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   \n",
       "5     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   \n",
       "6   Some college/university study without earning ...   \n",
       "7      Professional degree (JD, MD, Ph.D, Ed.D, etc.)   \n",
       "8        Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "9     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   \n",
       "10    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   \n",
       "11       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "12       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "13       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   \n",
       "14     Professional degree (JD, MD, Ph.D, Ed.D, etc.)   \n",
       "\n",
       "                                           Employment  \\\n",
       "0                                            Employed   \n",
       "1                                            Employed   \n",
       "2   Independent contractor, freelancer, or self-em...   \n",
       "3                                            Employed   \n",
       "4   Independent contractor, freelancer, or self-em...   \n",
       "5   Independent contractor, freelancer, or self-em...   \n",
       "6   Independent contractor, freelancer, or self-em...   \n",
       "7                                            Employed   \n",
       "8                                            Employed   \n",
       "9                                            Employed   \n",
       "10                                           Employed   \n",
       "11                                           Employed   \n",
       "12  Independent contractor, freelancer, or self-em...   \n",
       "13                                           Employed   \n",
       "14                                           Employed   \n",
       "\n",
       "                                       EmploymentAddl  WorkExp  \\\n",
       "0     Caring for dependents (children, elderly, etc.)      8.0   \n",
       "1                                                 NaN      2.0   \n",
       "2                                   None of the above     10.0   \n",
       "3                                   None of the above      4.0   \n",
       "4     Caring for dependents (children, elderly, etc.)     21.0   \n",
       "5   Caring for dependents (children, elderly, etc....     15.0   \n",
       "6                                   None of the above      9.0   \n",
       "7   Engaged in paid work (20-29 hours per week);Tr...     22.0   \n",
       "8   Caring for dependents (children, elderly, etc....      9.0   \n",
       "9                                   None of the above      7.0   \n",
       "10                                  None of the above      7.0   \n",
       "11                                  None of the above      3.0   \n",
       "12    Caring for dependents (children, elderly, etc.)     10.0   \n",
       "13    Caring for dependents (children, elderly, etc.)      6.0   \n",
       "14  Attending school (full-time);Attending school ...     15.0   \n",
       "\n",
       "                                      LearnCodeChoose  \\\n",
       "0   Yes, I am not new to coding but am learning ne...   \n",
       "1   Yes, I am not new to coding but am learning ne...   \n",
       "2   Yes, I am not new to coding but am learning ne...   \n",
       "3   Yes, I am not new to coding but am learning ne...   \n",
       "4   No, I am not new to coding and did not learn n...   \n",
       "5   Yes, I am not new to coding but am learning ne...   \n",
       "6   Yes, I am not new to coding but am learning ne...   \n",
       "7   Yes, I am not new to coding but am learning ne...   \n",
       "8   Yes, I am not new to coding but am learning ne...   \n",
       "9   Yes, I am not new to coding but am learning ne...   \n",
       "10  No, I am not new to coding and did not learn n...   \n",
       "11  No, I am not new to coding and did not learn n...   \n",
       "12  Yes, I am not new to coding but am learning ne...   \n",
       "13  Yes, I am not new to coding but am learning ne...   \n",
       "14  No, I am not new to coding and did not learn n...   \n",
       "\n",
       "                                            LearnCode  \\\n",
       "0   Online Courses or Certification (includes all ...   \n",
       "1   Online Courses or Certification (includes all ...   \n",
       "2   Online Courses or Certification (includes all ...   \n",
       "3   Other online resources (e.g. standard search, ...   \n",
       "4                                                 NaN   \n",
       "5   Online Courses or Certification (includes all ...   \n",
       "6   Videos (not associated with specific online co...   \n",
       "7   Books / Physical media;Technical documentation...   \n",
       "8   Online Courses or Certification (includes all ...   \n",
       "9   Other online resources (e.g. standard search, ...   \n",
       "10                                                NaN   \n",
       "11                                                NaN   \n",
       "12  Videos (not associated with specific online co...   \n",
       "13  Online Courses or Certification (includes all ...   \n",
       "14                                                NaN   \n",
       "\n",
       "                                          LearnCodeAI  ...  \\\n",
       "0   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "1   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "2   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "3   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "4   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "5   Yes, I learned how to use AI-enabled tools req...  ...   \n",
       "6   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "7   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "8   Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "9   No, I learned something that was not related t...  ...   \n",
       "10  Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "11  Yes, I learned how to use AI-enabled tools for...  ...   \n",
       "12  No, I learned something that was not related t...  ...   \n",
       "13  Yes, I learned how to use AI-enabled tools req...  ...   \n",
       "14  No, I learned something that was not related t...  ...   \n",
       "\n",
       "   AIAgentOrchestration  AIAgentOrchWrite AIAgentObserveSecure  \\\n",
       "0             Vertex AI               NaN                  NaN   \n",
       "1                   NaN               NaN                  NaN   \n",
       "2                   NaN               NaN                  NaN   \n",
       "3                   NaN               NaN                  NaN   \n",
       "4                   NaN               NaN                  NaN   \n",
       "5                   NaN               NaN                  NaN   \n",
       "6                   NaN               NaN               Sentry   \n",
       "7                   NaN               NaN                  NaN   \n",
       "8                   NaN               NaN                  NaN   \n",
       "9                   NaN               NaN                  NaN   \n",
       "10                  NaN         Spring AI                  NaN   \n",
       "11                  NaN               NaN                  NaN   \n",
       "12                  NaN               NaN                  NaN   \n",
       "13                  NaN               NaN                  NaN   \n",
       "14                  NaN               NaN                  NaN   \n",
       "\n",
       "   AIAgentObsWrite                                    AIAgentExternal  \\\n",
       "0              NaN                                            ChatGPT   \n",
       "1              NaN                                                NaN   \n",
       "2              NaN   ChatGPT;Claude Code;GitHub Copilot;Google Gemini   \n",
       "3              NaN                                ChatGPT;Claude Code   \n",
       "4              NaN                                                NaN   \n",
       "5              NaN                                     GitHub Copilot   \n",
       "6              NaN                  ChatGPT;Claude Code;Google Gemini   \n",
       "7              NaN                                                NaN   \n",
       "8              NaN                                                NaN   \n",
       "9              NaN                                                NaN   \n",
       "10             NaN  ChatGPT;Claude Code;GitHub Copilot;Microsoft C...   \n",
       "11             NaN                                                NaN   \n",
       "12             NaN                                                NaN   \n",
       "13             NaN                                                NaN   \n",
       "14             NaN                                                NaN   \n",
       "\n",
       "   AIAgentExtWrite                                            AIHuman  \\\n",
       "0              NaN                    When I don’t trust AI’s answers   \n",
       "1              NaN  When I don’t trust AI’s answers;When I want to...   \n",
       "2              NaN  When I don’t trust AI’s answers;When I want to...   \n",
       "3              NaN  When I don’t trust AI’s answers;When I want to...   \n",
       "4              NaN                    When I don’t trust AI’s answers   \n",
       "5              NaN  When I have ethical or security concerns about...   \n",
       "6              NaN  When I don’t trust AI’s answers;When I need he...   \n",
       "7              NaN  When I want to learn best practices;When I wan...   \n",
       "8              NaN                                                NaN   \n",
       "9              NaN  When I’m stuck and can’t explain the problem;W...   \n",
       "10             NaN  When I don’t trust AI’s answers;When I have et...   \n",
       "11             NaN  When I don’t trust AI’s answers;When I need qu...   \n",
       "12             NaN  When I want to fully understand something;When...   \n",
       "13             NaN                                                NaN   \n",
       "14             NaN   I don’t think I’ll need help from people anymore   \n",
       "\n",
       "                                               AIOpen  ConvertedCompYearly  \\\n",
       "0               Troubleshooting, profiling, debugging              61256.0   \n",
       "1                           All skills. AI is a flop.             104413.0   \n",
       "2   Understand how things actually work, problem s...              53061.0   \n",
       "3                                                 NaN              36197.0   \n",
       "4   critical thinking, the skill to define the tas...              60000.0   \n",
       "5        designing the architecture in the new domain             120000.0   \n",
       "6                                                 NaN               6240.0   \n",
       "7                           Innovation, system design              72000.0   \n",
       "8                                                 NaN              70000.0   \n",
       "9                                                 NaN               5400.0   \n",
       "10  Code writing. I know this sounds weird but you...              65691.0   \n",
       "11                                                NaN              14400.0   \n",
       "12                                                NaN               1099.0   \n",
       "13                                                NaN                  NaN   \n",
       "14                                 senior development                  NaN   \n",
       "\n",
       "    JobSat  \n",
       "0     10.0  \n",
       "1      9.0  \n",
       "2      8.0  \n",
       "3      6.0  \n",
       "4      7.0  \n",
       "5      7.0  \n",
       "6      6.0  \n",
       "7      6.0  \n",
       "8      8.0  \n",
       "9      4.0  \n",
       "10    10.0  \n",
       "11     8.0  \n",
       "12     7.0  \n",
       "13     6.0  \n",
       "14     9.0  \n",
       "\n",
       "[15 rows x 172 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"survey_results_public.csv\", low_memory=False)\n",
    "schema = pd.read_csv(\"survey_results_schema.csv\")\n",
    "\n",
    "df.head(15)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7ad1bf7f-34d4-4acf-ae77-be281261ca6a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>qid</th>\n",
       "      <th>qname</th>\n",
       "      <th>question</th>\n",
       "      <th>type</th>\n",
       "      <th>sub</th>\n",
       "      <th>sq_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_1</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>AI integration or AI Agent capabilities</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_2</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Easy-to-use API</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_3</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Robust and complete API</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_4</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Customizable and manageable codebase</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_5</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Reputation for quality</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_6</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Connected to an open-source project</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_7</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Good brand and public image</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_8</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Reliability and low latency</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_9</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Costs are manageable</td>\n",
       "      <td>9.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_13</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Other (please specify):</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>QID18</td>\n",
       "      <td>TechEndorse_13_TEXT</td>\n",
       "      <td>What attracts you to a technology or causes yo...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Other (please specify): - Text</td>\n",
       "      <td>13.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>QID19</td>\n",
       "      <td>TechOppose_1</td>\n",
       "      <td>What would turn you off or cause you to reject...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Lack of AI or AI agents</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>QID19</td>\n",
       "      <td>TechOppose_2</td>\n",
       "      <td>What would turn you off or cause you to reject...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Poor usability</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>QID19</td>\n",
       "      <td>TechOppose_3</td>\n",
       "      <td>What would turn you off or cause you to reject...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Lack of or sub-par API</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>QID19</td>\n",
       "      <td>TechOppose_5</td>\n",
       "      <td>What would turn you off or cause you to reject...</td>\n",
       "      <td>RO</td>\n",
       "      <td>Inefficient or time-costly</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      qid                qname  \\\n",
       "0   QID18        TechEndorse_1   \n",
       "1   QID18        TechEndorse_2   \n",
       "2   QID18        TechEndorse_3   \n",
       "3   QID18        TechEndorse_4   \n",
       "4   QID18        TechEndorse_5   \n",
       "5   QID18        TechEndorse_6   \n",
       "6   QID18        TechEndorse_7   \n",
       "7   QID18        TechEndorse_8   \n",
       "8   QID18        TechEndorse_9   \n",
       "9   QID18       TechEndorse_13   \n",
       "10  QID18  TechEndorse_13_TEXT   \n",
       "11  QID19         TechOppose_1   \n",
       "12  QID19         TechOppose_2   \n",
       "13  QID19         TechOppose_3   \n",
       "14  QID19         TechOppose_5   \n",
       "\n",
       "                                             question type  \\\n",
       "0   What attracts you to a technology or causes yo...   RO   \n",
       "1   What attracts you to a technology or causes yo...   RO   \n",
       "2   What attracts you to a technology or causes yo...   RO   \n",
       "3   What attracts you to a technology or causes yo...   RO   \n",
       "4   What attracts you to a technology or causes yo...   RO   \n",
       "5   What attracts you to a technology or causes yo...   RO   \n",
       "6   What attracts you to a technology or causes yo...   RO   \n",
       "7   What attracts you to a technology or causes yo...   RO   \n",
       "8   What attracts you to a technology or causes yo...   RO   \n",
       "9   What attracts you to a technology or causes yo...   RO   \n",
       "10  What attracts you to a technology or causes yo...   RO   \n",
       "11  What would turn you off or cause you to reject...   RO   \n",
       "12  What would turn you off or cause you to reject...   RO   \n",
       "13  What would turn you off or cause you to reject...   RO   \n",
       "14  What would turn you off or cause you to reject...   RO   \n",
       "\n",
       "                                        sub  sq_id  \n",
       "0   AI integration or AI Agent capabilities    1.0  \n",
       "1                           Easy-to-use API    2.0  \n",
       "2                   Robust and complete API    3.0  \n",
       "3      Customizable and manageable codebase    4.0  \n",
       "4                    Reputation for quality    5.0  \n",
       "5       Connected to an open-source project    6.0  \n",
       "6               Good brand and public image    7.0  \n",
       "7               Reliability and low latency    8.0  \n",
       "8                      Costs are manageable    9.0  \n",
       "9                   Other (please specify):   10.0  \n",
       "10           Other (please specify): - Text   13.0  \n",
       "11                  Lack of AI or AI agents    1.0  \n",
       "12                           Poor usability    2.0  \n",
       "13                   Lack of or sub-par API    3.0  \n",
       "14               Inefficient or time-costly    4.0  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "schema.head(15)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d75c524d-1c18-4b2d-8a3a-cab4322a9342",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "49191"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Task_1\n",
    "total_responds = df.shape[0]\n",
    "total_responds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "3a2a6fe5-4b55-4f0d-a5b5-4d50313b19e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    }
   ],
   "source": [
    "#Task_2\n",
    "questions = set(schema[\"qname\"])\n",
    "\n",
    "columns = set(df.columns)\n",
    "\n",
    "valid_columns = list(questions.intersection(columns))\n",
    "\n",
    "complete_responses = df[valid_columns].dropna().shape[0]\n",
    "print(complete_responses)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "7e24b3e7-02dd-4aa6-be2c-1ecddee17f31",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mean: 13.367402606485907\n",
      "Median: 10.0\n",
      "Mode: 10.0\n"
     ]
    }
   ],
   "source": [
    "#Task_3\n",
    "workexp = df[\"WorkExp\"]\n",
    "\n",
    "mean_val = workexp.mean()\n",
    "median_val = workexp.median()\n",
    "mode_val = workexp.mode()\n",
    "\n",
    "print(\"Mean:\", mean_val)\n",
    "print(\"Median:\", median_val)\n",
    "print(\"Mode:\", mode_val[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "0c4c61e8-a531-4154-9d1c-358fca002e45",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10931\n"
     ]
    }
   ],
   "source": [
    "#Task_4\n",
    "remote_count = df[df[\"RemoteWork\"] == \"Remote\"].shape[0]\n",
    "print(remote_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "073fd07d-1ef0-4045-98b0-1b8635b85199",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Відсоток респондентів, які програмують на Python:37.54%\n"
     ]
    }
   ],
   "source": [
    "#Task_5\n",
    "python_users = df[\"LanguageHaveWorkedWith\"].str.contains(\"Python\", na=False)\n",
    "\n",
    "percentage = python_users.mean() * 100\n",
    "print(f\"Відсоток респондентів, які програмують на Python: {percentage:.2f}%\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "7e0f1a43-e34b-4d23-8869-bfc971de4a44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10973\n"
     ]
    }
   ],
   "source": [
    "#Task_6\n",
    "online_learners = df[\"LearnCode\"].str.contains(\"Online Courses\", case=False, na=False)\n",
    "\n",
    "count_online = online_learners.sum()\n",
    "print(count_online)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "bf2d432d-0a9e-46e3-8f4c-6308331f24f7",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Country</th>\n",
       "      <th>Average_Compensation</th>\n",
       "      <th>Median_Compensation</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>22328.666667</td>\n",
       "      <td>1000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Albania</td>\n",
       "      <td>47217.600000</td>\n",
       "      <td>50000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Algeria</td>\n",
       "      <td>20187.285714</td>\n",
       "      <td>7088.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Andorra</td>\n",
       "      <td>226103.500000</td>\n",
       "      <td>226103.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Angola</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>162</th>\n",
       "      <td>Venezuela, Bolivarian Republic of...</td>\n",
       "      <td>9908.647059</td>\n",
       "      <td>3000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>163</th>\n",
       "      <td>Viet Nam</td>\n",
       "      <td>218837.166667</td>\n",
       "      <td>8254.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>164</th>\n",
       "      <td>Yemen</td>\n",
       "      <td>32929.500000</td>\n",
       "      <td>23672.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>165</th>\n",
       "      <td>Zambia</td>\n",
       "      <td>5424.250000</td>\n",
       "      <td>3206.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>166</th>\n",
       "      <td>Zimbabwe</td>\n",
       "      <td>34000.000000</td>\n",
       "      <td>25500.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>167 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                  Country  Average_Compensation  \\\n",
       "0                             Afghanistan          22328.666667   \n",
       "1                                 Albania          47217.600000   \n",
       "2                                 Algeria          20187.285714   \n",
       "3                                 Andorra         226103.500000   \n",
       "4                                  Angola                   NaN   \n",
       "..                                    ...                   ...   \n",
       "162  Venezuela, Bolivarian Republic of...           9908.647059   \n",
       "163                              Viet Nam         218837.166667   \n",
       "164                                 Yemen          32929.500000   \n",
       "165                                Zambia           5424.250000   \n",
       "166                              Zimbabwe          34000.000000   \n",
       "\n",
       "     Median_Compensation  \n",
       "0                 1000.0  \n",
       "1                50000.0  \n",
       "2                 7088.0  \n",
       "3               226103.5  \n",
       "4                    NaN  \n",
       "..                   ...  \n",
       "162               3000.0  \n",
       "163               8254.0  \n",
       "164              23672.0  \n",
       "165               3206.0  \n",
       "166              25500.0  \n",
       "\n",
       "[167 rows x 3 columns]"
      ]
     },
     "execution_count": 69,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Task_7\n",
    "python_df = df[df[\"LanguageHaveWorkedWith\"].str.contains(\"Python\", na=False)]\n",
    "\n",
    "salary_stats = python_df.groupby(\"Country\")[\"ConvertedCompYearly\"].agg(Average_Compensation=\"mean\", Median_Compensation=\"median\").reset_index()\n",
    "salary_stats"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "3c23f649-ee33-4a57-b002-b8c00178824b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ConvertedCompYearly</th>\n",
       "      <th>EdLevel</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>34267</th>\n",
       "      <td>50000000.0</td>\n",
       "      <td>Associate degree (A.A., A.S., etc.)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28700</th>\n",
       "      <td>33552715.0</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43143</th>\n",
       "      <td>18387548.0</td>\n",
       "      <td>Associate degree (A.A., A.S., etc.)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35353</th>\n",
       "      <td>15430267.0</td>\n",
       "      <td>Bachelor’s degree (B.A., B.S., B.Eng., etc.)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45971</th>\n",
       "      <td>13921760.0</td>\n",
       "      <td>Master’s degree (M.A., M.S., M.Eng., MBA, etc.)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       ConvertedCompYearly                                          EdLevel\n",
       "34267           50000000.0              Associate degree (A.A., A.S., etc.)\n",
       "28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)\n",
       "43143           18387548.0              Associate degree (A.A., A.S., etc.)\n",
       "35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)\n",
       "45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
      ]
     },
     "execution_count": 74,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Task_8\n",
    "top5 = df.sort_values(by=\"ConvertedCompYearly\", ascending=False).head(5)\n",
    "\n",
    "top5_education = top5[[\"ConvertedCompYearly\", \"EdLevel\"]]\n",
    "top5_education"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "id": "dff77727-919b-4ad0-ba64-593eb7c1634f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age_category</th>\n",
       "      <th>Python_percentage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>18-24 years old</td>\n",
       "      <td>40.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>25-34 years old</td>\n",
       "      <td>36.939282</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>35-44 years old</td>\n",
       "      <td>36.719281</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>45-54 years old</td>\n",
       "      <td>38.629482</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>55-64 years old</td>\n",
       "      <td>37.242955</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>65 years or older</td>\n",
       "      <td>31.634820</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Prefer not to say</td>\n",
       "      <td>31.216931</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        Age_category  Python_percentage\n",
       "0    18-24 years old          40.000000\n",
       "1    25-34 years old          36.939282\n",
       "2    35-44 years old          36.719281\n",
       "3    45-54 years old          38.629482\n",
       "4    55-64 years old          37.242955\n",
       "5  65 years or older          31.634820\n",
       "6  Prefer not to say          31.216931"
      ]
     },
     "execution_count": 78,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Task_9\n",
    "df[\"Python\"] = df[\"LanguageHaveWorkedWith\"].str.contains(\"Python\", na=False)\n",
    "\n",
    "age_python = df.groupby(\"Age\")[\"Python\"].mean().reset_index()\n",
    "age_python[\"Python\"] = age_python[\"Python\"] * 100\n",
    "\n",
    "age_python.columns = [\"Age_category\", \"Python_percentage\"]\n",
    "age_python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "a4f8dfaf-d6ea-4ddb-ad5f-f65f23a20b79",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Industry\n",
      "Software Development                          1186\n",
      "Fintech                                        190\n",
      "Healthcare                                     188\n",
      "Other:                                         176\n",
      "Internet, Telecomm or Information Services     138\n",
      "Banking/Financial Services                      88\n",
      "Government                                      78\n",
      "Media & Advertising Services                    75\n",
      "Retail and Consumer Services                    65\n",
      "Transportation, or Supply Chain                 63\n",
      "Computer Systems Design and Services            59\n",
      "Insurance                                       46\n",
      "Energy                                          45\n",
      "Manufacturing                                   33\n",
      "Higher Education                                30\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "#Task_10\n",
    "rich_percentile = df[\"ConvertedCompYearly\"].quantile(0.75)\n",
    "\n",
    "filtered = df[\n",
    "    (df[\"ConvertedCompYearly\"] >= rich_percentile) &\n",
    "    (df[\"RemoteWork\"] == \"Remote\")]\n",
    "\n",
    "top_industries = filtered[\"Industry\"].value_counts()\n",
    "print(top_industries)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0a1ead9-efe2-430f-a9db-d372327e3e30",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
